#!/bin/bash

echo -n "Sisestage reisijate arv: "
read reisijad

echo -n "Sisestage kohtade arv bussis: "
read kohad

bussid=$(($reisijad / $kohad))
mahajaab=$(($reisijad % $kohad))

echo "$reisijad-reisja transportimiseks saab kasutada $bussid-te $kohad-list bussi, mahajääb $mahajaab inimest."

