#!/bin/bash

read -p "Sisestage kuu number: " kuu
#Kontrollib, kas sisestatud kuu on vahemikus 3-5
if test $kuu -ge 3 -a $kuu -le 5
then
	echo "Praegu on kevad!"
#Kontrollib, kas sisestatud kuu on vahemikus 6-8
elif test $kuu -ge 6 -a $kuu -le 8
then
	echo "Praegu on suvi!"
#Kontrollib, kas sisestatud kuu on vahemikus 9-11
elif test $kuu -ge 9 -a $kuu -le 11
then
	echo "Praegu on sügis"
#Kontrollib, kas sisestatud kuu on väiksem, kui 12
elif test $kuu -le 12
then
#Kuna ainukesed kuud, mis on järgi on kõik talve omad, võime väljastada, et antud kuu on talve oma
	echo "Praegu on talv!"

else
	echo "Antud numbriga kuud ei ole!"
fi
