#!/bin/bash

#Võtab kasutaja nime, hiljem kirjutab selle üle ja muudab esitähe suureks.
kasutaja=$(whoami)
kasutaja=${kasutaja^}
#Võtab kellast ainult tunni väärtuse.
aeg=$(date +%H)

#Kontrollib, kas sisestatud aeg on vahemikus 6-11
if test $aeg -ge 6 -a $aeg -lt 12; then
	echo "Tere hommikust, $kasutaja!"
#Kontrollib, kas sisestatud aeg on vahemikus 12-17
elif test $aeg -ge 12 -a $aeg -lt 18; then
	echo "Tere päevast, $kasutaja!"
#Kontrollib kas antud aeg on vahemikus 18-21
elif test $aeg -ge 18 -a $aeg -lt 22; then
        echo "Tere, õhtust, $kasutaja!"
#Võtab kõik ülejäänud ajad, mis on väiksemad, kui 24
elif test $aeg -le 23;then
	echo "Head, ööd!"
#Vale sisestuse korral, ütleb kasutajale
else
	echo "Vale sisend"

fi
