#!/bin/bash

#Kontrollib kas skripti käivitamisel on kaasa antud mingi väärtus.
if [ $# != 1 ]
then
#Kui ei ole antud väärtust palub kasutajal sisestada skriptiga mõni arv
	echo "Käivita skript koos arvuga, mille paarsust soovid kontrollida."
else
#Kui on antud väärtus hakkab kontrollima selle paaris või paaritus olekut.
	arv=$1
	jaak=$(($arv % 2))
	if [ $jaak == 0 ]
	then
		echo "$arv on paaris."
	else
		echo "$arv on paaritu."
	fi
fi
